name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: deploy/checkout@v1

      - name: executing remote ssh commands using password
        uses: ./
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          #port: ${{ secrets.PORT }}
          script: whoami
